apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: etl-ecrater
  name: etl-ecrater
spec:
  schedule: "0 0 */2 * *"
  timeZone: "GMT"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 0
      template:
        metadata:
          labels:
            app: etl-ecrater
        spec:
          containers:
            - args:
                - -finalbucket
                - temporal-data-mammals
                - -task
                - text-classification
                - -col
                - title
                - -filename
                - crawl-ecrater-temporal
                - -temporal
                - "true"
              name: etl-data
              image: julesbarbosa/load_hub:15
              imagePullPolicy: Always
              command: ["python3", "main_disk.py"]
              resources:
                limits:
                  nvidia.com/gpu: 1
              env:
              - name: HUGGINGFACE_API_KEY
                value: xxxxxx
              - name: MINIO_KEY
                value: xxxxxx
              - name: MINIO_SECRET
                value: xxxxxx
              volumeMounts:
                - mountPath: /data
                  name: etl-data-ecrater
          restartPolicy: OnFailure
          tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule
          volumes:
            - name: etl-data-ecrater
              persistentVolumeClaim:
                claimName: etl-data-ecrater

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etl-data-ecrater
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  dataSource:
    kind: PersistentVolumeClaim
    name: ache-claim-ecrater

